wownero/wownero

- src/cryptonote_basic/difficulty.cpp
Changed size_t  to match solvetime
> Update LWMA difficulty algorithm

- src/crypto/slow-hash.c
credit: 
https://github.com/monero-project/monero/pull/3696/
https://github.com/seredat/karbowanec/issues/41
> fix memory leak for Windows

- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
> clean up defaultMixin for wallet api

- README.md
https://gitlab.com/fdroid/fdroiddata/merge_requests/3496#note_93903961
> clarify license status

- src/wallet/api/wallet.cpp
Reference: https://github.com/monero-project/monero/pull/3735
> Fixed building with Boost 1.67

- contrib/epee/include/storages/portable_storage_from_bin.h
- contrib/epee/include/storages/portable_storage_from_json.h
- src/wallet/wallet2.cpp
https://getmonero.org/2018/09/25/a-post-mortum-of-the-burning-bug.html
> DoS/RPC fixes [#4438]

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
Removed ability to make integrated addresses at the wallet level.. added nag message to use subaddresses. 
Issue: #102
> Wallet: encourage use of subaddresses

- src/cryptonote_basic/difficulty.cpp
- src/cryptonote_basic/difficulty.h
- src/cryptonote_config.h
- src/cryptonote_core/blockchain.cpp
Stop use of negative solvetimes, change blockchain timestamp check window to 11
> add LWMA v3 for v10 HF

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/CMakeLists.txt
- src/wallet/message_store.cpp
- src/wallet/message_store.h
- src/wallet/message_transporter.cpp
- src/wallet/message_transporter.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_errors.h
After two rounds of quite intense testing on Testnet and Mainnet (thanks again to all involved) and improvements done based on testing results plus a rebasing to latest 0.3.0.0 code I can finally make a PR for the MMS, Wownero edition.
> MMS for Wownero

- src/cryptonote_basic/cryptonote_boost_serialization.h
- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/cryptonote_core/tx_pool.cpp
- src/ringct/CMakeLists.txt
- src/ringct/bulletproofs.h
- src/ringct/bulletproofs2.cc
- src/ringct/rctSigs.cpp
- src/ringct/rctSigs.h
- src/ringct/rctTypes.cpp
- src/ringct/rctTypes.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
- src/wallet/wallet2.cpp
Applied the patches from https://github.com/italocoin-project/italo/commit/6cebd0004534128344aebe50087d228ae685e109 and https://github.com/italocoin-project/italo/commit/1bc8afec2550c438cfdfb299e173d7b6472fa4f0 to rebase.
Requires further review and testing
> Support old bulletproof

- src/cryptonote_basic/cryptonote_format_utils.cpp
fix: https://github.com/wownero/wownero/commit/389d2bc53ea0f6ffe16b9789bc786e494411673e#r31751630
> remove V.clear

- cmake/CheckTrezor.cmake
> disable Trezor support

- tests/README.md
> fixed tests/README.md

- Makefile
> enable tests in debug

- src/simplewallet/simplewallet.cpp
> randomize churn time

- src/cryptonote_basic/difficulty.cpp
- src/cryptonote_basic/difficulty.h
- src/cryptonote_core/blockchain.cpp
> difficulty: revert to int64_t

- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_core/cryptonote_core.cpp
- src/ringct/rctSigs.cpp
- src/ringct/rctTypes.cpp
- src/ringct/rctTypes.h
- src/wallet/wallet2.cpp
> Fix tx error on testnet2

- src/wallet/wallet2.cpp
> [need testing] hotfix "no ring" error in wallet

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/p2p/net_node.cpp
- src/p2p/net_node.inl
> Revert "allow sync over tor"

- CMakeLists.txt
- external/CMakeLists.txt
- src/checkpoints/checkpoints.cpp
- src/common/CMakeLists.txt
- src/common/updates.cpp
- src/common/util.cpp
- src/cryptonote_basic/cryptonote_basic_impl.cpp
- src/daemon/command_parser_executor.cpp
- src/p2p/net_node.inl
- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet_manager.cpp
- src/wallet/wallet2.cpp
Reverted the changes since they might be useful somewhere.
> Remove remove unbound

- contrib/epee/include/console_handler.h
- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/epee/include/net/http_server_impl_base.h
- contrib/epee/include/storages/levin_abstract_invoke2.h
- src/blockchain_utilities/blocksdat_file.h
- src/blockchain_utilities/bootstrap_file.h
- src/checkpoints/checkpoints.cpp
- src/device_trezor/trezor/transport.cpp
- src/p2p/net_node.inl
- src/rpc/rpc_args.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- tests/core_tests/chaingen.h
> Fix boost compatibility

- src/daemon/rpc_command_executor.cpp
> mining_status print output

- README.md
wow! such source based! many compile
> readme: Add Gentoo install instructions
